// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Fetch the signed-in user's SmartCard profile (username, title, bio, theme, plan).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "id, username, title, bio, avatar_url, theme_name, plan, social_links, onboarded, updated_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No profile found for this account yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";
var update_my_profile_default = defineTool2({
  name: "update_my_profile",
  title: "Update my profile",
  description: "Update the signed-in user's profile fields (title, bio, username, avatar URL).",
  inputSchema: {
    title: z.string().trim().max(120).optional().describe("Display name / headline."),
    bio: z.string().trim().max(1e3).optional().describe("Short bio shown on the public profile."),
    username: z.string().trim().regex(/^[a-zA-Z0-9_-]{3,30}$/).optional().describe("Public handle used in the profile URL."),
    avatar_url: z.string().url().optional().describe("Public URL of the avatar image.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = Object.fromEntries(
      Object.entries(input).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").update({ ...patch, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("user_id", ctx.getUserId()).select("id, username, title, bio, avatar_url").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No profile found to update." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-links.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_my_links_default = defineTool3({
  name: "list_my_links",
  title: "List my links",
  description: "List all links on the signed-in user's SmartCard profile, in display order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("links").select("id, title, url, visible, position, click_count, is_featured").eq("user_id", ctx.getUserId()).order("position", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { links: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_link_default = defineTool4({
  name: "create_link",
  title: "Create link",
  description: "Add a new link button to the signed-in user's SmartCard profile.",
  inputSchema: {
    title: z2.string().trim().min(1).max(120).describe("Button label."),
    url: z2.string().trim().min(1).describe("Destination URL (https://, tel:, mailto:, etc.)."),
    visible: z2.boolean().optional().describe("Whether the link is shown publicly. Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, url, visible }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: last } = await supabase.from("links").select("position").eq("user_id", userId).order("position", { ascending: false }).limit(1).maybeSingle();
    const { data, error } = await supabase.from("links").insert({
      user_id: userId,
      title,
      url,
      visible: visible ?? true,
      position: (last?.position ?? -1) + 1
    }).select("id, title, url, visible, position").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { link: data }
    };
  }
});

// src/lib/mcp/tools/update-link.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var update_link_default = defineTool5({
  name: "update_link",
  title: "Update link",
  description: "Update the title, URL, visibility, or position of one of the signed-in user's links.",
  inputSchema: {
    id: z3.string().uuid().describe("ID of the link to update."),
    title: z3.string().trim().min(1).max(120).optional(),
    url: z3.string().trim().min(1).optional(),
    visible: z3.boolean().optional(),
    position: z3.number().int().min(0).optional().describe("Display order (0 = first).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== void 0));
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("links").update({ ...patch, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id).eq("user_id", ctx.getUserId()).select("id, title, url, visible, position").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Link not found for this account." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { link: data }
    };
  }
});

// src/lib/mcp/tools/delete-link.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var delete_link_default = defineTool6({
  name: "delete_link",
  title: "Delete link",
  description: "Permanently delete one of the signed-in user's profile links.",
  inputSchema: { id: z4.string().uuid().describe("ID of the link to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("links").delete().eq("id", id).eq("user_id", ctx.getUserId()).select("id, title").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Link not found for this account." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted link "${data.title}".` }],
      structuredContent: { deleted: data }
    };
  }
});

// src/lib/mcp/tools/get-profile-stats.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_profile_stats_default = defineTool7({
  name: "get_profile_stats",
  title: "Get profile stats",
  description: "Summarize the signed-in user's profile performance: total views and link clicks over the last N days.",
  inputSchema: {
    days: z5.number().int().min(1).max(365).optional().describe("Lookback window in days (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = days ?? 30;
    const since = new Date(Date.now() - window * 24 * 60 * 60 * 1e3).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("id, username").eq("user_id", ctx.getUserId()).maybeSingle();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    if (!profile) {
      return { content: [{ type: "text", text: "No profile found for this account yet." }] };
    }
    const [views, clicks, links] = await Promise.all([
      supabase.from("profile_views").select("id", { count: "exact", head: true }).eq("profile_id", profile.id).gte("viewed_at", since),
      supabase.from("link_clicks").select("id", { count: "exact", head: true }).eq("profile_id", profile.id).gte("clicked_at", since),
      supabase.from("links").select("title, click_count").eq("user_id", ctx.getUserId()).order("click_count", { ascending: false }).limit(5)
    ]);
    const summary = {
      username: profile.username,
      window_days: window,
      views: views.count ?? 0,
      link_clicks: clicks.count ?? 0,
      top_links: links.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ezflznozfbmrzxepfndu";
var mcp_default = defineMcp({
  name: "smartcardsa",
  title: "SmartCardSA",
  version: "0.1.0",
  instructions: "Tools for SmartCardSA digital business cards. Read and edit the signed-in user's profile, manage their SmartLink buttons, and review profile view/click stats.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    update_my_profile_default,
    list_my_links_default,
    create_link_default,
    update_link_default,
    delete_link_default,
    get_profile_stats_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
